## scraping data

In [12]:
import requests
from bs4 import BeautifulSoup

In [17]:
def scrape():
    url = 'https://www.treasury.gov/resource-center/data-chart-center/interest-rates/Pages/TextView.aspx?data=yield'
    response = requests.get(url).text
    soup = BeautifulSoup(response)
    table = soup.find("table", attrs={"class": "t-chart"})

    #printing the entire table
    #print(table.prettify())
    
    #getting every row of table
    trs = table.findAll("tr")
    
    #getting the column names
    col_names = table.findAll("th")
    column_name = [names.text for names in col_names]
    
    #getting the data on the table, excluding column names
    data = []
    for item in trs:
        td_tag = item.findAll('td')
        for tag in td_tag:
            data.append(tag.text)
    
    #converting data to list of lists and saving final list as data_lst
    length = len(column_name)
    dates = len(data) //length
    data_lst = []
    j = 0
    for i in range(dates):
        row = data[j: j+ length]
        data_lst.append(row)
        j +=13
    return data_lst

scrape()

[['04/01/21',
  '0.02',
  '0.02',
  '0.02',
  '0.04',
  '0.06',
  '0.17',
  '0.35',
  '0.90',
  '1.37',
  '1.69',
  '2.24',
  '2.34'],
 ['04/02/21',
  '0.02',
  '0.02',
  '0.02',
  '0.04',
  '0.07',
  '0.19',
  '0.39',
  '0.97',
  '1.42',
  '1.72',
  '2.27',
  '2.35'],
 ['04/05/21',
  '0.03',
  '0.02',
  '0.03',
  '0.04',
  '0.06',
  '0.17',
  '0.37',
  '0.94',
  '1.40',
  '1.73',
  '2.28',
  '2.36'],
 ['04/06/21',
  '0.02',
  '0.02',
  '0.02',
  '0.04',
  '0.06',
  '0.16',
  '0.35',
  '0.88',
  '1.34',
  '1.67',
  '2.24',
  '2.32'],
 ['04/07/21',
  '0.01',
  '0.02',
  '0.02',
  '0.04',
  '0.06',
  '0.16',
  '0.34',
  '0.87',
  '1.34',
  '1.68',
  '2.26',
  '2.35'],
 ['04/08/21',
  '0.02',
  '0.02',
  '0.01',
  '0.04',
  '0.05',
  '0.14',
  '0.33',
  '0.85',
  '1.30',
  '1.64',
  '2.22',
  '2.32'],
 ['04/09/21',
  '0.02',
  '0.01',
  '0.02',
  '0.03',
  '0.06',
  '0.16',
  '0.35',
  '0.87',
  '1.33',
  '1.67',
  '2.23',
  '2.34'],
 ['04/12/21',
  '0.02',
  '0.02',
  '0.02',
  '0.04',
  '0.06',
  '0.18',
  '0.38',
  '0.89',
  '1.35',
  '1.69',
  '2.24',
  '2.34'],
 ['04/13/21',
  '0.03',
  '0.02',
  '0.03',
  '0.05',
  '0.06',
  '0.16',
  '0.35',
  '0.85',
  '1.29',
  '1.64',
  '2.21',
  '2.32'],
 ['04/14/21',
  '0.02',
  '0.02',
  '0.02',
  '0.04',
  '0.06',
  '0.16',
  '0.35',
  '0.87',
  '1.31',
  '1.64',
  '2.22',
  '2.32'],
 ['04/15/21',
  '0.02',
  '0.01',
  '0.02',
  '0.04',
  '0.06',
  '0.16',
  '0.32',
  '0.81',
  '1.24',
  '1.56',
  '2.13',
  '2.23'],
 ['04/16/21',
  '0.02',
  '0.02',
  '0.02',
  '0.04',
  '0.06',
  '0.16',
  '0.34',
  '0.84',
  '1.26',
  '1.59',
  '2.15',
  '2.26'],
 ['04/19/21',
  '0.01',
  '0.02',
  '0.02',
  '0.04',
  '0.08',
  '0.16',
  '0.34',
  '0.85',
  '1.28',
  '1.61',
  '2.18',
  '2.29'],
 ['04/20/21',
  '0.01',
  '0.02',
  '0.03',
  '0.04',
  '0.07',
  '0.15',
  '0.31',
  '0.81',
  '1.25',
  '1.58',
  '2.16',
  '2.27'],
 ['04/21/21',
  '0.00',
  '0.02',
  '0.03',
  '0.04',
  '0.07',
  '0.15',
  '0.32',
  '0.81',
  '1.24',
  '1.57',
  '2.16',
  '2.26'],
 ['04/22/21',
  '0.02',
  '0.02',
  '0.03',
  '0.04',
  '0.06',
  '0.16',
  '0.32',
  '0.81',
  '1.24',
  '1.57',
  '2.13',
  '2.24']]

### Printing every row of table

In [13]:
trs = table.findAll("tr")

### Getting the names of the columns in table

In [14]:
col_names = table.findAll("th")
column_name = [names.text for names in col_names]
print(column_name)

['Date', '1 mo', '2 mo', '3 mo', '6 mo', '1 yr', '2 yr', '3 yr', '5 yr', '7 yr', '10 yr', '20 yr', '30 yr']

### Printing data on the table, excluding the column names

In [15]:
data = []
for item in trs:
    td_tag = item.findAll('td')
    for tag in td_tag:
        data.append(tag.text)
print(data)

['04/01/21', '0.02', '0.02', '0.02', '0.04', '0.06', '0.17', '0.35', '0.90', '1.37', '1.69', '2.24', '2.34', '04/02/21', '0.02', '0.02', '0.02', '0.04', '0.07', '0.19', '0.39', '0.97', '1.42', '1.72', '2.27', '2.35', '04/05/21', '0.03', '0.02', '0.03', '0.04', '0.06', '0.17', '0.37', '0.94', '1.40', '1.73', '2.28', '2.36', '04/06/21', '0.02', '0.02', '0.02', '0.04', '0.06', '0.16', '0.35', '0.88', '1.34', '1.67', '2.24', '2.32', '04/07/21', '0.01', '0.02', '0.02', '0.04', '0.06', '0.16', '0.34', '0.87', '1.34', '1.68', '2.26', '2.35', '04/08/21', '0.02', '0.02', '0.01', '0.04', '0.05', '0.14', '0.33', '0.85', '1.30', '1.64', '2.22', '2.32', '04/09/21', '0.02', '0.01', '0.02', '0.03', '0.06', '0.16', '0.35', '0.87', '1.33', '1.67', '2.23', '2.34', '04/12/21', '0.02', '0.02', '0.02', '0.04', '0.06', '0.18', '0.38', '0.89', '1.35', '1.69', '2.24', '2.34', '04/13/21', '0.03', '0.02', '0.03', '0.05', '0.06', '0.16', '0.35', '0.85', '1.29', '1.64', '2.21', '2.32', '04/14/21', '0.02', '0.02', '0.02', '0.04', '0.06', '0.16', '0.35', '0.87', '1.31', '1.64', '2.22', '2.32', '04/15/21', '0.02', '0.01', '0.02', '0.04', '0.06', '0.16', '0.32', '0.81', '1.24', '1.56', '2.13', '2.23', '04/16/21', '0.02', '0.02', '0.02', '0.04', '0.06', '0.16', '0.34', '0.84', '1.26', '1.59', '2.15', '2.26', '04/19/21', '0.01', '0.02', '0.02', '0.04', '0.08', '0.16', '0.34', '0.85', '1.28', '1.61', '2.18', '2.29', '04/20/21', '0.01', '0.02', '0.03', '0.04', '0.07', '0.15', '0.31', '0.81', '1.25', '1.58', '2.16', '2.27', '04/21/21', '0.00', '0.02', '0.03', '0.04', '0.07', '0.15', '0.32', '0.81', '1.24', '1.57', '2.16', '2.26', '04/22/21', '0.02', '0.02', '0.03', '0.04', '0.06', '0.16', '0.32', '0.81', '1.24', '1.57', '2.13', '2.24']

#### Making data into lists

In [21]:
len(data) //13

14

In [16]:
length = len(column_name)
dates= len(data) //length
data_lst = []
j = 0
for i in range(dates):
    row = data[j: j+ length]
    data_lst.append(row)
    j +=13
    
print(data_lst)

[['04/01/21', '0.02', '0.02', '0.02', '0.04', '0.06', '0.17', '0.35', '0.90', '1.37', '1.69', '2.24', '2.34'], ['04/02/21', '0.02', '0.02', '0.02', '0.04', '0.07', '0.19', '0.39', '0.97', '1.42', '1.72', '2.27', '2.35'], ['04/05/21', '0.03', '0.02', '0.03', '0.04', '0.06', '0.17', '0.37', '0.94', '1.40', '1.73', '2.28', '2.36'], ['04/06/21', '0.02', '0.02', '0.02', '0.04', '0.06', '0.16', '0.35', '0.88', '1.34', '1.67', '2.24', '2.32'], ['04/07/21', '0.01', '0.02', '0.02', '0.04', '0.06', '0.16', '0.34', '0.87', '1.34', '1.68', '2.26', '2.35'], ['04/08/21', '0.02', '0.02', '0.01', '0.04', '0.05', '0.14', '0.33', '0.85', '1.30', '1.64', '2.22', '2.32'], ['04/09/21', '0.02', '0.01', '0.02', '0.03', '0.06', '0.16', '0.35', '0.87', '1.33', '1.67', '2.23', '2.34'], ['04/12/21', '0.02', '0.02', '0.02', '0.04', '0.06', '0.18', '0.38', '0.89', '1.35', '1.69', '2.24', '2.34'], ['04/13/21', '0.03', '0.02', '0.03', '0.05', '0.06', '0.16', '0.35', '0.85', '1.29', '1.64', '2.21', '2.32'], ['04/14/21', '0.02', '0.02', '0.02', '0.04', '0.06', '0.16', '0.35', '0.87', '1.31', '1.64', '2.22', '2.32'], ['04/15/21', '0.02', '0.01', '0.02', '0.04', '0.06', '0.16', '0.32', '0.81', '1.24', '1.56', '2.13', '2.23'], ['04/16/21', '0.02', '0.02', '0.02', '0.04', '0.06', '0.16', '0.34', '0.84', '1.26', '1.59', '2.15', '2.26'], ['04/19/21', '0.01', '0.02', '0.02', '0.04', '0.08', '0.16', '0.34', '0.85', '1.28', '1.61', '2.18', '2.29'], ['04/20/21', '0.01', '0.02', '0.03', '0.04', '0.07', '0.15', '0.31', '0.81', '1.25', '1.58', '2.16', '2.27'], ['04/21/21', '0.00', '0.02', '0.03', '0.04', '0.07', '0.15', '0.32', '0.81', '1.24', '1.57', '2.16', '2.26'], ['04/22/21', '0.02', '0.02', '0.03', '0.04', '0.06', '0.16', '0.32', '0.81', '1.24', '1.57', '2.13', '2.24']]

In [ ]:
def setup_db():
    data = scrape()
    db.drop_all()
    db.create_all()
    for lst in data:
        row = TreasuryYieldTable(date = data_lst[0], one_mo = data_lst[1], two_mo = data_lst[2], three_mo = data_lst[3], six_month = data_lst[4], 
                        one_year = data_lst[5], two_year = data_lst[6], three_year = data_lst[7], five_year = data_lst[8], seven_year =data_lst[9], ten_year = data_lst[10],
                        twenty_year = data_lst[11], thirty_year = data_lst[12])
        db.session.add(row)
        db.session.commit()